### ISSUE TITLE
nifi Unable to resolve required dependency

### ISSUE THREAD

**Issue by glisignoli** [Asymmetrik/nifi-nar-bundles#20]
Building from source I get the following error:

WARN [main] org.apache.nifi.nar.NarClassLoaders Unable to resolve required dependency 'nifi-standard-services-api-nar'. Skipping NAR '/opt/apache-nifi/./work/nar/extensions/nifi-influxdb-service-nar-0.5.4-SNAPSHOT.nar-unpacked'

This happens for all nar files in this bundle.

**Comment by brianghig** [comment]
@glisignoli Does this happen during the build, or within NiFi when you're starting it up? If it's during startup, what version of NiFi are you running? Thanks!

**Comment by glisignoli** [comment]
@brianghig This happens during nifi startup. I'm using Nifi 1.5.0.

I'm assuming it's because all the apache nifi nars are versioned now? I'm really not sure if that's the cause or not:

INFO [main] org.apache.nifi.nar.NarClassLoaders Loaded NAR file: /opt/apache-nifi/./work/nar/extensions/nifi-standard-services-api-nar-1.5.0.nar-unpacked as class loader org.apache.nifi.nar.NarClassLoader[./work/nar/extensions/nifi-standard-services-api-nar-1.5.0.nar-unpacked]

**Comment by brianghig** [comment]
@glisignoli thanks for the information! That might be the case - I haven't tested this with NiFi 1.5 yet. However, we saw something similar when going from NiFi 1.3 to 1.4 that made me believe that the NAR bundles need to be compiled for that particular version of NiFi.

On this current 0.5.4-SNAPSHOT version, you'll see in the top-level pom.xml in this repo that we're targetting nifi.version "1.3". You may have luck changing that to "1.5" and rebuilding / redeploying the NARs. I can't test that myself at the moment, but please let me know if you find that does the trick!

**Comment by glisignoli** [comment]
@brianghig Yep that worked! Thanks!

**Comment by brianghig** [comment]
@glisignoli Wonderful! Thanks for checking it out. I'll close out this ticket for now and we'll keep an eye on anything in NiFi that would help us build multi-version NARs moving forward.
