### ISSUE TITLE
No controller service types found for InfluxNifiClusterMetricsReporter

### ISSUE THREAD

**Issue by glisignoli** [Asymmetrik/nifi-nar-bundles#8]
When trying to setup a 'InfluxNifiClusterMetricsReporter' I am unable to set a InfluxDB service (no suggestions show up). I am also unable to select any 'InfluxDbService' 'Reporting task controller services' that are created.

**Comment by rstjohn** [comment]
This issue was being resolved under a different ticket and the PR was just merged (https://github.com/Asymmetrik/nifi-nar-bundles/pull/7) and the release tag was moved to 0.5.2.

**Comment by rstjohn** [comment]
I've verified that this issue has been resolved.  Thanks!
