### ISSUE TITLE
Allow reporting on all entities

### ISSUE THREAD

**Issue by glisignoli** [Asymmetrik/nifi-nar-bundles#9]
It would be a nice to be able to specify wildcards, or just report on every processor/connections/groups if properties are left empty

**Comment by rstjohn** [comment]
are you thinking of regex?  What about a drop-down with options [All, Componenets Specified Below]?

**Comment by glisignoli** [comment]
Hmm I'm not sure. Being able to just report on all components (.*) would be ideal for myself. Since I can just use influx to filter on what I want. It also means if a new nifi flow is added then I don't need to update the influxreporter with the new name or id.

**Comment by rstjohn** [comment]
How about this: no value means all, empty string means none and text means exact match.  If you like that, I'll make sure it's clear in the docs

**Comment by glisignoli** [comment]
Yep that would be awesome. I also noticed that you can specify a processor id or name. So that would be good to document as well

**Comment by rstjohn** [comment]
Will do.  I've already started making the changes.  I'll have a PR soon-ish.
